[package]
name = "bench-windows"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
win-perf = []

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
*** End of File
